exclude: ^(1-security/for_bootstrap|2-workload/for_bootstrap)/
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.77.1 
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
